array:
  M: 8
data:
  T: 100
  K: 4
  DOA_SOI_range:
    - -90
    - 90
  SNR_range:
    - -10
    - 10
  SNR_spacing: 2
  n_samples: 20000
  MC_trials: 500
train:
  num_epochs: 50
  batch_size: 256
  scale: 5.0
  wd: 0.0
  lr: 4.e-4 
  lr_gamma: 0.5
  lr_milestones:
    - 22
    - 26
    - 40
rng:
  data_random_state:
  train_random_state:
  test_random_state:
dirs:
  data_dir: "data"
  model_dir: "model"
  train_dir: "train"
  test_dir: "test"